
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Thu Oct 27 16:35:51 CEST 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAROUVRE = 4;
  public static final int SOMME = 2;
  public static final int EOL = 8;
  public static final int MULT = 3;
  public static final int VARIABLECHAINE = 12;
  public static final int EOF = 0;
  public static final int EGAL = 6;
  public static final int VARIABLECHIFFRE = 11;
  public static final int ENTIER = 9;
  public static final int error = 1;
  public static final int PRINT = 7;
  public static final int PARFERME = 5;
  public static final int CHAINE = 10;
}

